# Generated by Django 3.0.4 on 2020-05-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
